### ISSUE TITLE
Monkeypatch and multi threading

### ISSUE THREAD

**Issue by InputError** [Anorov/PySocks#99]
Is it possible to use different proxies in each thread when I am doing monkey patching?

Or only single proxy per all threads is possible?

**Comment by Anorov** [comment]
I don't believe it's possible. Monkeypatching is considered very hacky and is not well-supported by Python.

You can call the usual `socks` functions and methods from each thread, with different proxy arguments. If you're using a module that creates its own sockets, you may need to look for a way to pass in your own socket objects.

Worst case, if you do want to monkeypatch, you could spawn multiple Python processes instead of multiple threads.
